services:
    bot:
        image: tvnn-qol-bot
        container_name: bot
        env_file:
            - ./.env
        restart: unless-stopped
        # entrypoint: /bin/sh
        # command: -c "sleep 3600"
    telegram-bot-api:
        image: aiogram/telegram-bot-api
        container_name: telegram-bot-api
        ports:
            - "8081:8081"
        env_file:
            - ./.env
        restart: unless-stopped
    bgutil:
        image: brainicism/bgutil-ytdlp-pot-provider:sha-3c6d642
        container_name: bgutil-provider
        ports:
            - "127.0.0.1:4416:4416"
        restart: unless-stopped
